version: '3'

services:

  LinuxAD:
    image: easylinux/samba-ad-dc
    volumes:
      - AD:/AD
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager

  Smtp:
    image: easylinux/mailserver:smtp
    volumes:
      - MAILS:/Data
    ports:
      - 25:25

  Imap:
    image: easylinux/mailserver:imap
    volumes:
      - MAILS:/Data
    ports:
      - 143:143

volumes:
  AD:
  MAILS:
