version: '3'

services:

  LinuxAD:
    image: easylinux/mailserver:ad
    volumes:
      - AD:/AD
    cap_add:
      - SYS_ADMIN
#    deploy:
#      placement:
#        constraints:
#          - node.role == manager

  Smtp:
    image: easylinux/mailserver:smtp
    volumes:
      - MAILS:/Data
    ports:
      - 25:25

  Imap:
    image: easylinux/mailserver:imap
    volumes:
      - MAILS:/Data
    ports:
      - 143:143

  Portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - PORTAINER:/data

volumes:
  AD:
  MAILS:
  PORTAINER:
